### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by opwa** [amdonov/lite-idp#14]
I tried to build a simple authentication application and got SIGSEGV from lite-idp. The application used python3-saml and flask as sp and lite-idp as idp.

The workflow of the application:
- Flask service provider starts
- Idp-lite servers
- idp-lite adds flask as service provider
- Flask requests the idp metadata (custom code) to add idp configuration
- Flask sends the metadata xml
- SIGSEGV from lite-idp

Easily reproducable example, add configurations to files in same folder with provided names and run `docker-compose up`

docker-compose.yml
```
version: "3.7"
services:
  flask.local:
    build:
      dockerfile: flask
      context: .
    ports:
      - 8000:8000
    networks:
      - backend

  idp.local:
    build:
      dockerfile: idp
      context: .
    ports:
      - 9443:9443
    networks:
      - backend
    depends_on:
      - flask.local

networks:
  backend:
```

flask
```
FROM ubuntu:18.04
# APT
RUN apt update
RUN apt install -y git python3 python3-pip libxmlsec1-dev pkg-config
# Clone
RUN git clone https://github.com/onelogin/python3-saml.git/
WORKDIR /python3-saml
# Requirements
RUN pip3 install -r demo-flask/requirements.txt
RUN python3 setup.py install
# Configuration
RUN sed -i 's|https://<sp_domain>|http://flask.local:8000|g' demo-flask/saml/settings.json
# Custom code
RUN sed -i 's|auth = O.*|from onelogin.saml2.auth import OneLogin_Saml2_Settings\n    from onelogin.saml2.idp_metadata_parser import OneLogin_Saml2_IdPMetadataParser\n    import json\n\n    parsed=OneLogin_Saml2_IdPMetadataParser.parse_remote("https://idp.local:9443/metadata",validate_cert=False)\n\n    json_data_file=open(app.config["SAML_PATH"]+"/settings.json","r")\n    settings_data=json.load(json_data_file)\n    json_data_file.close()\n\n    merged=OneLogin_Saml2_IdPMetadataParser.merge_settings(settings_data,parsed)\n    auth=OneLogin_Saml2_Auth(req,merged)\n\n    return auth|' demo-flask/index.py
# Start
CMD python3 demo-flask/index.py
```

idp
```
FROM golang:rc-alpine3.10
RUN apk add git gcc make libc-dev openssl
RUN git clone https://github.com/amdonov/lite-idp.git /go/src/myapp/lite-idp
WORKDIR /go/src/myapp/lite-idp/hack/tls-setup
RUN make
WORKDIR /go/src/myapp/lite-idp
RUN echo >> config.yaml
RUN echo "listen-address: 0.0.0.0:9443" >> config.yaml
RUN echo "server-name: idp.local:9443" >> config.yaml
RUN go build main.go
CMD ./main serve & sleep 1 && ./main add service-provider http://flask.local:8000/metadata/ && fg
```

stack trace
```
flask.local_1  |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
flask.local_1  |  * Restarting with stat
flask.local_1  |  * Debugger is active!
flask.local_1  |  * Debugger PIN: 340-222-474
idp.local_1    | using config file: /go/src/myapp/lite-idp/config.yaml
idp.local_1    | using the built-in ui assets
idp.local_1    | time="2019-07-17T08:03:03Z" level=info msg="listening for connections on 0.0.0.0:9443"
idp.local_1    | using config file: /go/src/myapp/lite-idp/config.yaml
idp.local_1    | 192.168.128.2 - - [17/Jul/2019:08:03:04 +0000] "GET /metadata HTTP/1.1" 200 8995 "" "Python-urllib/3.6"
flask.local_1  | 192.168.128.3 - - [17/Jul/2019 08:03:04] "GET /metadata/ HTTP/1.1" 200 -
idp.local_1    | panic: runtime error: invalid memory address or nil pointer dereference
idp.local_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8db2de]
idp.local_1    | 
idp.local_1    | goroutine 1 [running]:
idp.local_1    | github.com/amdonov/lite-idp/idp.convertMetadata(0xc00018c000, 0x9784a0)
idp.local_1    |        /go/src/myapp/lite-idp/idp/sp.go:69 +0x4e
idp.local_1    | github.com/amdonov/lite-idp/idp.ReadSPMetadata(0xb3d780, 0xc0000b69c0, 0xc0000b69c0, 0xb3d780, 0xc0000b69c0)
idp.local_1    |        /go/src/myapp/lite-idp/idp/sp.go:64 +0xbf
idp.local_1    | github.com/amdonov/lite-idp/cmd.glob..func2(0x143fac0, 0xc000097950, 0x1, 0x1, 0x0, 0x0)
idp.local_1    |        /go/src/myapp/lite-idp/cmd/serviceProvider.go:44 +0x105
idp.local_1    | github.com/spf13/cobra.(*Command).execute(0x143fac0, 0xc000097930, 0x1, 0x1, 0x143fac0, 0xc000097930)
idp.local_1    |        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x42c
idp.local_1    | github.com/spf13/cobra.(*Command).ExecuteC(0x143fce0, 0xa6eec0, 0x7, 0xa63840)
idp.local_1    |        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2c9
idp.local_1    | github.com/spf13/cobra.(*Command).Execute(...)
idp.local_1    |        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
idp.local_1    | main.Execute()
idp.local_1    |        /go/src/myapp/lite-idp/main.go:38 +0x31
idp.local_1    | main.main()
idp.local_1    |        /go/src/myapp/lite-idp/main.go:79 +0x148
example_idp.local_1 exited with code 2
```

**Comment by amdonov** [comment]
Sorry for the delayed response. I didn't see this ticket come in. 

The code that parses SP metadata could obviously use some more checks. I'll work to get those added. In the meantime, it doesn't like your SP metadata. It's failing to find the certificate information. It expects the metadata to have a very specific structure. You can see an example at https://github.com/amdonov/lite-idp/blob/master/idp/testdata/sp-metadata.xml. Please compare that to your metadata.
